# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Customer'),
        ),
    ]
