# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Center'),
        ),
    ]
