# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_auto_20161012_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlXml', models.FilePathField(max_length=200)),
                ('date', models.DateTimeField()),
                ('done', models.BooleanField()),
            ],
        ),
    ]
