# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_mailstoprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailstoprocess',
            name='urlXml',
        ),
        migrations.AddField(
            model_name='mailstoprocess',
            name='xml_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
