# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 23:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0005_auto_20161015_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('mac_address', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=200)),
                ('toner_level', models.CharField(max_length=200)),
                ('pages_printed', models.IntegerField(blank=True)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Printer')),
            ],
        ),
    ]
