# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_printerreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerreport',
            name='pages_printed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printerreport',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='printerreport',
            name='toner_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
