# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_alert_alertattributes_alertemailgroup_alertemailgrouprecivers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printerreport',
            old_name='printer',
            new_name='printerOwner',
        ),
        migrations.AddField(
            model_name='printer',
            name='last_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.PrinterReport'),
        ),
    ]
