# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0012_auto_20161031_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
