# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0014_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
