# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-14 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0015_alert_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='printerOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.Printer'),
        ),
        migrations.AddField(
            model_name='printerreport',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
