# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 15:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0016_auto_20161114_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('mono', 'Mono'), ('color', 'Color')], default='mono', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alerttype',
            field=models.CharField(choices=[('[alert-toner]', 'Alerta de Toner Bajo'), ('[alert-no_report]', 'Alerta de No reporte recibido')], max_length=200),
        ),
        migrations.AlterField(
            model_name='alertemailgroup',
            name='alerttype',
            field=models.CharField(choices=[('[alert-toner]', 'Alerta de Toner Bajo'), ('[alert-no_report]', 'Alerta de No reporte recibido')], max_length=200),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="El formato para el campo es el siguiente: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message="El formato para el campo es el siguiente: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
