# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 19:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0018_auto_20161204_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='host_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, validators=[django.core.validators.validate_ipv46_address]),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
