# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0019_auto_20161204_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
